/**
 * 根據常見的副檔名指派圖示
 */
const extensionIconMap: Record<string, `codicon codicon-${string}`> = {
  // Web 相關
  html: "codicon codicon-browser",
  htm: "codicon codicon-browser",
  xhtml: "codicon codicon-browser",
  css: "codicon codicon-file-code",
  scss: "codicon codicon-file-code",
  sass: "codicon codicon-file-code",
  less: "codicon codicon-file-code",

  // JavaScript / TypeScript
  js: "codicon codicon-file-code",
  mjs: "codicon codicon-file-code",
  cjs: "codicon codicon-file-code",
  jsx: "codicon codicon-file-code",
  ts: "codicon codicon-file-code",
  tsx: "codicon codicon-file-code",
  d: "codicon codicon-file-code",
  "d.ts": "codicon codicon-file-code",

  // 其他程式語言
  php: "codicon codicon-file-code",
  py: "codicon codicon-file-code",
  pyw: "codicon codicon-file-code",
  pyc: "codicon codicon-file-code",
  ipynb: "codicon codicon-file-code",
  java: "codicon codicon-file-code",
  class: "codicon codicon-file-code",
  jar: "codicon codicon-package",
  c: "codicon codicon-file-code",
  cpp: "codicon codicon-file-code",
  cc: "codicon codicon-file-code",
  cxx: "codicon codicon-file-code",
  h: "codicon codicon-file-code",
  hpp: "codicon codicon-file-code",
  cs: "codicon codicon-file-code",
  go: "codicon codicon-file-code",
  rs: "codicon codicon-file-code",
  rb: "codicon codicon-file-code",
  swift: "codicon codicon-file-code",
  kt: "codicon codicon-file-code",
  scala: "codicon codicon-file-code",
  dart: "codicon codicon-file-code",
  lua: "codicon codicon-file-code",
  r: "codicon codicon-file-code",
  m: "codicon codicon-file-code",
  pl: "codicon codicon-file-code",
  sh: "codicon codicon-terminal",
  bash: "codicon codicon-terminal",
  zsh: "codicon codicon-terminal",
  fish: "codicon codicon-terminal",
  ps1: "codicon codicon-terminal",
  bat: "codicon codicon-terminal",
  cmd: "codicon codicon-terminal",

  // 數據格式
  json: "codicon codicon-file-code",
  jsonc: "codicon codicon-file-code",
  json5: "codicon codicon-file-code",
  yaml: "codicon codicon-file-code",
  yml: "codicon codicon-file-code",
  xml: "codicon codicon-file-code",
  toml: "codicon codicon-file-code",
  csv: "codicon codicon-file-code",

  // 文檔
  md: "codicon codicon-file-text",
  markdown: "codicon codicon-file-text",
  txt: "codicon codicon-file-text",
  rtf: "codicon codicon-file-text",
  doc: "codicon codicon-file-text",
  docx: "codicon codicon-file-text",
  odt: "codicon codicon-file-text",
  tex: "codicon codicon-file-text",
  log: "codicon codicon-file-text",

  // 配置文件
  ini: "codicon codicon-gear",
  conf: "codicon codicon-gear",
  config: "codicon codicon-gear",
  properties: "codicon codicon-gear",
  env: "codicon codicon-gear",
  editorconfig: "codicon codicon-gear",
  gitignore: "codicon codicon-gear",
  dockerignore: "codicon codicon-gear",
  npmrc: "codicon codicon-gear",
  eslintrc: "codicon codicon-gear",

  // 資料庫
  db: "codicon codicon-database",
  sql: "codicon codicon-database",
  sqlite: "codicon codicon-database",
  sqlite3: "codicon codicon-database",
  mdb: "codicon codicon-database",

  // 3D / 圖形
  blend: "codicon codicon-symbol-method",
  blend1: "codicon codicon-archive",
  obj: "codicon codicon-symbol-method",
  fbx: "codicon codicon-symbol-method",
  dae: "codicon codicon-symbol-method",
  stl: "codicon codicon-symbol-method",
  gltf: "codicon codicon-symbol-method",
  glb: "codicon codicon-symbol-method",
  spp: "codicon codicon-symbol-color",
  psd: "codicon codicon-symbol-color",
  ai: "codicon codicon-symbol-color",
  sketch: "codicon codicon-symbol-color",
  fig: "codicon codicon-symbol-color",
  xd: "codicon codicon-symbol-color",

  // 圖片
  png: "codicon codicon-file-media",
  jpg: "codicon codicon-file-media",
  jpeg: "codicon codicon-file-media",
  webp: "codicon codicon-file-media",
  gif: "codicon codicon-file-media",
  svg: "codicon codicon-file-media",
  tiff: "codicon codicon-file-media",
  tif: "codicon codicon-file-media",
  bmp: "codicon codicon-file-media",
  ico: "codicon codicon-file-media",
  icns: "codicon codicon-file-media",
  heic: "codicon codicon-file-media",
  heif: "codicon codicon-file-media",
  raw: "codicon codicon-file-media",
  cr2: "codicon codicon-file-media",
  nef: "codicon codicon-file-media",

  // 音訊
  mp3: "codicon codicon-file-media",
  wav: "codicon codicon-file-media",
  flac: "codicon codicon-file-media",
  aac: "codicon codicon-file-media",
  ogg: "codicon codicon-file-media",
  wma: "codicon codicon-file-media",
  m4a: "codicon codicon-file-media",
  opus: "codicon codicon-file-media",

  // 影片
  mp4: "codicon codicon-file-media",
  mov: "codicon codicon-file-media",
  avi: "codicon codicon-file-media",
  mkv: "codicon codicon-file-media",
  flv: "codicon codicon-file-media",
  wmv: "codicon codicon-file-media",
  webm: "codicon codicon-file-media",
  m4v: "codicon codicon-file-media",
  mpeg: "codicon codicon-file-media",
  mpg: "codicon codicon-file-media",

  // PDF
  pdf: "codicon codicon-file-pdf",

  // 壓縮檔
  zip: "codicon codicon-file-zip",
  rar: "codicon codicon-file-zip",
  tar: "codicon codicon-file-zip",
  gz: "codicon codicon-file-zip",
  bz2: "codicon codicon-file-zip",
  xz: "codicon codicon-file-zip",
  "7z": "codicon codicon-file-zip",
  tgz: "codicon codicon-file-zip",
  bak: "codicon codicon-archive",
  old: "codicon codicon-archive",

  // 可執行檔 / 套件
  exe: "codicon codicon-package",
  msi: "codicon codicon-package",
  app: "codicon codicon-package",
  dmg: "codicon codicon-package",
  deb: "codicon codicon-package",
  rpm: "codicon codicon-package",
  apk: "codicon codicon-package",
  vsix: "codicon codicon-package",

  // 字型
  ttf: "codicon codicon-symbol-string",
  otf: "codicon codicon-symbol-string",
  woff: "codicon codicon-symbol-string",
  woff2: "codicon codicon-symbol-string",
  eot: "codicon codicon-symbol-string",

  // 其他
  lock: "codicon codicon-lock",
  key: "codicon codicon-key",
  pem: "codicon codicon-key",
  crt: "codicon codicon-key",
  cert: "codicon codicon-key",
  gpg: "codicon codicon-key",
  dll: "codicon codicon-library",
  so: "codicon codicon-library",
  dylib: "codicon codicon-library",
  iso: "codicon codicon-file-zip",
  img: "codicon codicon-file-zip",
};

export { extensionIconMap };
